package com.chengxin.netdiskdemo.dataobject;

import java.util.Date;

public class FileTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_table.id
     *
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_table.file_check_code
     *
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    private String fileCheckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_table.local_path
     *
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    private String localPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_table.size
     *
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    private Double size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_table.create_time
     *
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_table.modify_time
     *
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_table.id
     *
     * @return the value of file_table.id
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_table.id
     *
     * @param id the value for file_table.id
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_table.file_check_code
     *
     * @return the value of file_table.file_check_code
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public String getFileCheckCode() {
        return fileCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_table.file_check_code
     *
     * @param fileCheckCode the value for file_table.file_check_code
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public void setFileCheckCode(String fileCheckCode) {
        this.fileCheckCode = fileCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_table.local_path
     *
     * @return the value of file_table.local_path
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public String getLocalPath() {
        return localPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_table.local_path
     *
     * @param localPath the value for file_table.local_path
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_table.size
     *
     * @return the value of file_table.size
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public Double getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_table.size
     *
     * @param size the value for file_table.size
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public void setSize(Double size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_table.create_time
     *
     * @return the value of file_table.create_time
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_table.create_time
     *
     * @param createTime the value for file_table.create_time
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_table.modify_time
     *
     * @return the value of file_table.modify_time
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_table.modify_time
     *
     * @param modifyTime the value for file_table.modify_time
     * @mbg.generated Fri Mar 13 17:27:49 GMT+08:00 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}