package com.chengxin.netdiskdemo.dataobject;

import java.util.Date;

public class UserFileTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.id
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.account
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.file_name
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.father_folder
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private String fatherFolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.file_type
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.is_delete
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.file_check_code
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private String fileCheckCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.id
     *
     * @return the value of user_file_table.id
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.id
     *
     * @param id the value for user_file_table.id
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.account
     *
     * @return the value of user_file_table.account
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.account
     *
     * @param account the value for user_file_table.account
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.file_name
     *
     * @return the value of user_file_table.file_name
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.file_name
     *
     * @param fileName the value for user_file_table.file_name
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.father_folder
     *
     * @return the value of user_file_table.father_folder
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public String getFatherFolder() {
        return fatherFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.father_folder
     *
     * @param fatherFolder the value for user_file_table.father_folder
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setFatherFolder(String fatherFolder) {
        this.fatherFolder = fatherFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.file_type
     *
     * @return the value of user_file_table.file_type
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.file_type
     *
     * @param fileType the value for user_file_table.file_type
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.is_delete
     *
     * @return the value of user_file_table.is_delete
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.is_delete
     *
     * @param isDelete the value for user_file_table.is_delete
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.file_check_code
     *
     * @return the value of user_file_table.file_check_code
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public String getFileCheckCode() {
        return fileCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.file_check_code
     *
     * @param fileCheckCode the value for user_file_table.file_check_code
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setFileCheckCode(String fileCheckCode) {
        this.fileCheckCode = fileCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.create_time
     *
     * @return the value of user_file_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.create_time
     *
     * @param createTime the value for user_file_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file_table.modify_time
     *
     * @return the value of user_file_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file_table.modify_time
     *
     * @param modifyTime the value for user_file_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}