package com.chengxin.netdiskdemo.dataobject;

import java.util.Date;

public class UserTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.id
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.account
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.password
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.is_active
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    private String isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.id
     *
     * @return the value of user_table.id
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.id
     *
     * @param id the value for user_table.id
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.account
     *
     * @return the value of user_table.account
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.account
     *
     * @param account the value for user_table.account
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.password
     *
     * @return the value of user_table.password
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.password
     *
     * @param password the value for user_table.password
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.is_active
     *
     * @return the value of user_table.is_active
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.is_active
     *
     * @param isActive the value for user_table.is_active
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.create_time
     *
     * @return the value of user_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.create_time
     *
     * @param createTime the value for user_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.modify_time
     *
     * @return the value of user_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.modify_time
     *
     * @param modifyTime the value for user_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:28:43 GMT+08:00 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}