package com.chengxin.netdiskdemo.dataobject;

import java.util.Date;

public class UserDiskCapacityTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_disk_capacity_table.id
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_disk_capacity_table.account
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_disk_capacity_table.is_vip
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    private String isVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_disk_capacity_table.used_disk
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    private Double usedDisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_disk_capacity_table.capacity
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    private Double capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_disk_capacity_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_disk_capacity_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_disk_capacity_table.id
     *
     * @return the value of user_disk_capacity_table.id
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_disk_capacity_table.id
     *
     * @param id the value for user_disk_capacity_table.id
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_disk_capacity_table.account
     *
     * @return the value of user_disk_capacity_table.account
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_disk_capacity_table.account
     *
     * @param account the value for user_disk_capacity_table.account
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_disk_capacity_table.is_vip
     *
     * @return the value of user_disk_capacity_table.is_vip
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public String getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_disk_capacity_table.is_vip
     *
     * @param isVip the value for user_disk_capacity_table.is_vip
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public void setIsVip(String isVip) {
        this.isVip = isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_disk_capacity_table.used_disk
     *
     * @return the value of user_disk_capacity_table.used_disk
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public Double getUsedDisk() {
        return usedDisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_disk_capacity_table.used_disk
     *
     * @param usedDisk the value for user_disk_capacity_table.used_disk
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public void setUsedDisk(Double usedDisk) {
        this.usedDisk = usedDisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_disk_capacity_table.capacity
     *
     * @return the value of user_disk_capacity_table.capacity
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public Double getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_disk_capacity_table.capacity
     *
     * @param capacity the value for user_disk_capacity_table.capacity
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_disk_capacity_table.create_time
     *
     * @return the value of user_disk_capacity_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_disk_capacity_table.create_time
     *
     * @param createTime the value for user_disk_capacity_table.create_time
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_disk_capacity_table.modify_time
     *
     * @return the value of user_disk_capacity_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_disk_capacity_table.modify_time
     *
     * @param modifyTime the value for user_disk_capacity_table.modify_time
     *
     * @mbg.generated Thu Mar 12 16:29:34 GMT+08:00 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}