package com.chengxin.netdiskdemo.dao;


import com.chengxin.netdiskdemo.dataobject.FileTable;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface FileTableMapper {




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Delete({
        "delete from file_table",
        "where id = #{id,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Insert({
        "insert into file_table (id, file_check_code, ",
        "local_path, create_time, ",
        "modify_time)",
        "values (#{id,jdbcType=CHAR}, #{fileCheckCode,jdbcType=CHAR}, ",
        "#{localPath,jdbcType=VARCHAR}, now(), ",
        "now())"
    })
    int insert(FileTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Select({
        "select",
        "id, file_check_code, local_path, create_time, modify_time",
        "from file_table",
        "where id = #{id,jdbcType=CHAR}"
    })
    @Results(id = "fileMap",value = {
            @Result(column="id", property="id", jdbcType=JdbcType.CHAR, id=true),
            @Result(column="file_check_code", property="fileCheckCode", jdbcType=JdbcType.CHAR),
            @Result(column="local_path", property="localPath", jdbcType=JdbcType.VARCHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="modify_time", property="modifyTime", jdbcType=JdbcType.TIMESTAMP)
    })
    FileTable selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Select({
        "select",
        "id, file_check_code, local_path, create_time, modify_time",
        "from file_table"
    })
    @ResultMap(value = {"fileMap"})
    List<FileTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Update({
        "update file_table",
        "set file_check_code = #{fileCheckCode,jdbcType=CHAR},",
          "local_path = #{localPath,jdbcType=VARCHAR},",
          "modify_time = now()",
        "where id = #{id,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(FileTable record);
}