package com.chengxin.netdiskdemo.dao;


import com.chengxin.netdiskdemo.dataobject.FileTable;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface FileTableMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Delete({
            "delete from file_table",
            "where id = #{id,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Insert({
            "insert into file_table (id, file_check_code, ",
            "local_path, size, ",
            "create_time, modify_time)",
            "values (#{id,jdbcType=CHAR}, #{fileCheckCode,jdbcType=CHAR}, ",
            "#{localPath,jdbcType=VARCHAR}, #{size,jdbcType=DOUBLE}, ",
            "now(), now())"
    })
    int insert(FileTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Select({
            "select",
            "id, file_check_code, local_path, size,create_time, modify_time",
            "from file_table",
            "where id = #{id,jdbcType=CHAR}"
    })
    @Results(id = "fileMap", value = {
            @Result(column = "id", property = "id", jdbcType = JdbcType.CHAR, id = true),
            @Result(column = "file_check_code", property = "fileCheckCode", jdbcType = JdbcType.CHAR),
            @Result(column = "local_path", property = "localPath", jdbcType = JdbcType.VARCHAR),
            @Result(column = "size", property = "size", jdbcType = JdbcType.DOUBLE),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "modify_time", property = "modifyTime", jdbcType = JdbcType.TIMESTAMP)
    })
    FileTable selectByPrimaryKey(String id);


    @Select({
            "select",
            "id, file_check_code, local_path, size, create_time, modify_time",
            "from file_table",
            "where file_check_code = #{checkCode,jdbcType=VARCHAR}"
    })
    @ResultMap(value = {"fileMap"})
    FileTable selectByCheckCode(String checkCode);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Select({
            "select",
            "id, file_check_code, local_path, size, create_time, modify_time",
            "from file_table"
    })
    @ResultMap(value = {"fileMap"})
    List<FileTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_table
     *
     * @mbg.generated Thu Mar 12 16:30:15 GMT+08:00 2020
     */
    @Update({
            "update file_table",
            "set file_check_code = #{fileCheckCode,jdbcType=CHAR},",
            "local_path = #{localPath,jdbcType=VARCHAR},",
            "size = #{size,jdbcType=DOUBLE},",
            "modify_time = now()",
            "where id = #{id,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(FileTable record);
}