package com.chengxin.netdiskdemo.dao;

import com.chengxin.netdiskdemo.dataobject.UserFileTable;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface UserFileTableMapper {




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_table
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    @Delete({
        "delete from user_file_table",
        "where id = #{id,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_table
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    @Insert({
        "insert into user_file_table (id, account, ",
        "file_name, father_folder, ",
        "file_type, is_delete, file_check_code, ",
        "create_time, modify_time)",
        "values (#{id,jdbcType=CHAR}, #{account,jdbcType=VARCHAR}, ",
        "#{fileName,jdbcType=VARCHAR}, #{fatherFolder,jdbcType=VARCHAR}, ",
        "#{fileType,jdbcType=CHAR}, #{isDelete,jdbcType=CHAR}, #{fileCheckCode,jdbcType=CHAR}, ",
        "now(), now())"
    })
    int insert(UserFileTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_table
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    @Select({
        "select",
        "id, account, file_name, father_folder, file_type, is_delete, file_check_code, ",
        "create_time, modify_time",
        "from user_file_table",
        "where id = #{id,jdbcType=CHAR}"
    })
    @Results(id = "userFileMap",value = {
            @Result(column="id", property="id", jdbcType=JdbcType.CHAR, id=true),
            @Result(column="account", property="account", jdbcType=JdbcType.VARCHAR),
            @Result(column="file_name", property="fileName", jdbcType=JdbcType.VARCHAR),
            @Result(column="father_folder", property="fatherFolder", jdbcType=JdbcType.VARCHAR),
            @Result(column="file_type", property="fileType", jdbcType=JdbcType.CHAR),
            @Result(column="is_delete", property="isDelete", jdbcType=JdbcType.CHAR),
            @Result(column="file_check_code", property="fileCheckCode", jdbcType=JdbcType.CHAR),
            @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="modify_time", property="modifyTime", jdbcType=JdbcType.TIMESTAMP)
    })
    UserFileTable selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_table
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    @Select({
        "select",
        "id, account, file_name, father_folder, file_type, is_delete, file_check_code, ",
        "create_time, modify_time",
        "from user_file_table"
    })
    @ResultMap(value = {"userFileMap"})
    List<UserFileTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file_table
     *
     * @mbg.generated Thu Mar 12 16:29:07 GMT+08:00 2020
     */
    @Update({
        "update user_file_table",
        "set account = #{account,jdbcType=VARCHAR},",
          "file_name = #{fileName,jdbcType=VARCHAR},",
          "father_folder = #{fatherFolder,jdbcType=VARCHAR},",
          "file_type = #{fileType,jdbcType=CHAR},",
          "is_delete = #{isDelete,jdbcType=CHAR},",
          "file_check_code = #{fileCheckCode,jdbcType=CHAR},",
          "modify_time = now()",
        "where id = #{id,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(UserFileTable record);
}